data_ingestion:
  train_ratio : 0.8

data_processing:
  categorical_columns:
  - channel_name
  - category
  - Sub-category
  - Customer Remarks
  - order_date_time
  - Issue_reported at
  - issue_responded'
  - Survey_response_Date
  - Customer_City
  - Product_category
  - Agent_name
  - Supervisor
  - Manager
  - Agent Shift

  numerical_columns:
  - Item_price
  - Tenure Bucket
  - CSAT Score
  - missing_order_time
  - missing_report_time
  - missing_response_time
  - response_time_hours
  - order_to_issue_hours
  - survey_delay_hours
   